# Site settings
title: UNC ENPA MSDS Repo
email: services@unc.edu
description: > # this means to ignore newlines until "baseurl:"
  This is a repository to hold all of our MSDS sheets, organized by labs.
  Any problems or updates should be reported.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  sjmeijer

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
